export const fruits = [
    "Apple",
    "Banana",
    "Orange",
    "Mango",
    "Pineapple",
    "Strawberry",
    "Blueberry",
    "Raspberry",
    "Blackberry",
    "Cherry",
    "Peach",
    "Pear",
    "Plum",
    "Grapes",
    "Watermelon",
    "Cantaloupe",
    "Honeydew",
    "Papaya",
    "Kiwi",
    "Pomegranate",
    "Fig",
    "Date",
    "Coconut",
    "Avocado",
    "Guava",
    "Lychee",
    "Dragon Fruit",
    "Passion Fruit",
    "Starfruit",
    "Persimmon",
    "Cranberry",
    "Gooseberry",
    "Mulberry",
    "Jackfruit",
    "Durian",
    "Tamarind",
    "Kumquat",
    "Apricot",
    "Nectarine",
    "Elderberry",
    "Acai Berry",
    "Salak (Snake Fruit)",
    "Jujube",
    "Soursop",
    "Longan",
    "Mangosteen",
    "Chico (Sapodilla)",
    "Miracle Fruit",
    "Rambutan",
    "Breadfruit",
  ];